// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612191905_AddConstraintsAndPrecisions")]
    partial class AddConstraintsAndPrecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BiodataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agama")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("agama");

                    b.Property<string>("AlamatKtp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alamat_ktp");

                    b.Property<string>("AlamatTinggal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alamat_tinggal");

                    b.Property<bool>("BersediaDitempatkan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bersedia_ditempatkan");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GolonganDarah")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("golongan_darah");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("jenis_kelamin");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nama");

                    b.Property<string>("NoKtp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("no_ktp");

                    b.Property<string>("NoTelp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("no_telp");

                    b.Property<string>("OrangTerdekat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("orang_terdekat");

                    b.Property<decimal?>("PenghasilanDiharapkan")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("penghasilan_diharapkan");

                    b.Property<string>("PosisiDilamar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("posisi_dilamar");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("skill");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_lahir");

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tempat_lahir");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("NoKtp")
                        .IsUnique()
                        .HasFilter("[no_ktp] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("biodata", null, t =>
                        {
                            t.HasCheckConstraint("CK_Biodata_Penghasilan", "penghasilan_diharapkan > 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PekerjaanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int")
                        .HasColumnName("biodata_id");

                    b.Property<string>("NamaPerusahaan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nama_perusahaan");

                    b.Property<decimal?>("PendapatanTerakhir")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("pendapatan_terakhir");

                    b.Property<string>("PosisiTerakhir")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("posisi_terakhir");

                    b.Property<int?>("Tahun")
                        .HasColumnType("int")
                        .HasColumnName("tahun");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("pekerjaan", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pekerjaan_Pendapatan", "pendapatan_terakhir >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PelatihanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int")
                        .HasColumnName("biodata_id");

                    b.Property<string>("NamaKursus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nama_kursus");

                    b.Property<string>("Sertifikat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sertifikat");

                    b.Property<int?>("Tahun")
                        .HasColumnType("int")
                        .HasColumnName("tahun");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("pelatihan", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PendidikanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BiodataId")
                        .HasColumnType("int")
                        .HasColumnName("biodata_id");

                    b.Property<decimal?>("Ipk")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("ipk");

                    b.Property<string>("Jenjang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("jenjang");

                    b.Property<string>("Jurusan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jurusan");

                    b.Property<string>("NamaInstitusi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nama_institusi");

                    b.Property<int?>("TahunLulus")
                        .HasColumnType("int")
                        .HasColumnName("tahun_lulus");

                    b.HasKey("Id");

                    b.HasIndex("BiodataId");

                    b.ToTable("pendidikan", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pendidikan_Ipk", "ipk >= 0 AND ipk <= 4");
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("USER")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "role IN ('USER', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.BiodataEntity", b =>
                {
                    b.HasOne("Domain.Entities.UserEntity", "User")
                        .WithOne("Biodata")
                        .HasForeignKey("Domain.Entities.BiodataEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PekerjaanEntity", b =>
                {
                    b.HasOne("Domain.Entities.BiodataEntity", "Biodata")
                        .WithMany("Pekerjaan")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("Domain.Entities.PelatihanEntity", b =>
                {
                    b.HasOne("Domain.Entities.BiodataEntity", "Biodata")
                        .WithMany("Pelatihan")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("Domain.Entities.PendidikanEntity", b =>
                {
                    b.HasOne("Domain.Entities.BiodataEntity", "Biodata")
                        .WithMany("Pendidikan")
                        .HasForeignKey("BiodataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biodata");
                });

            modelBuilder.Entity("Domain.Entities.BiodataEntity", b =>
                {
                    b.Navigation("Pekerjaan");

                    b.Navigation("Pelatihan");

                    b.Navigation("Pendidikan");
                });

            modelBuilder.Entity("Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Biodata");
                });
#pragma warning restore 612, 618
        }
    }
}
